### ISSUE TITLE
Greasemonkey Script

### ISSUE THREAD

**Issue by Riajyuu** [fregante/github-clean-feed#10]
Could you release this as a Greasemonkey Script and post it to greasyfork.org ?

**Comment by fregante** [comment]
Why use Greasemonkey when you have a real extension?

**Comment by Riajyuu** [comment]
Some one (not me) may prefer such a solution if a task can be done without frequent options changing

**Comment by fregante** [comment]
Adjusting/removing Chrome APIs is not an easy task. There's little interest in GitHub Clean Feed, it's not worth it for me. You're free to create and maintain a Greasemonkey fork.
