### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by Riajyuu** [fregante/github-clean-feed#2]
I totally understand some words are native in English for GitHub.

But some stings some be actually localized, e.g. function descriptions, texts used on AMO.

If youare to add locale support, when you're ready, drop me [email](mailto:EMLVIRUS@outlook.com). I would like to help the Zh-CN locale.

Plus I also suggest you post this extension on [babelzilla](https://www.babelzilla.org/index.php) to get more locale help.

**Comment by fregante** [comment]
That sounds good! Can you send me a PR? I worked on an extension that had it before, perhaps you can take example from that: https://github.com/HangYang/one-click-extensions-manager

I think the only thing that needs localization is the `options.html` page and a single word in the feed: `by`

**Comment by Riajyuu** [comment]
> options.html

I'm sorry, I can find `index.html` and `options-init.js`. Where is `options.html` ?

**Comment by fregante** [comment]
Sorry I meant `options/index.html`

**Comment by Riajyuu** [comment]
Got it. And where are texts used on AMO/chrome store extension page?
Are they unnecessay to be localized?

**Comment by fregante** [comment]
AMO doesn't have much text at all. The issue with translating those is that I'd have to manually copy and paste any change in every language, I don't see any way to include them in the uploaded zip file.

**Comment by fregante** [comment]
In the HTML file, this approach is preferred:

```json
{
   "starred-repos-title": {
       "message": "Starred repositories"
   }
}
```

```html
<h3 data-i18n="starred-repos-title"></h3>
```

```js
for (const el of document.querySelectorAll('[data-i18n]')) {
    el.textContent = chrome.i18n.getMessage(el.getAttribute('data-i18n'));
}
```

**Comment by fregante** [comment]
Added! Please create your `_locales/zh-cn/messages.json` file by copying this file:

https://github.com/bfred-it/github-clean-feed/blob/master/extension/_locales/en/messages.json

**Comment by fregante** [comment]
Reopening because of https://github.com/bfred-it/github-clean-feed/pull/4#issuecomment-305957553

**Comment by fregante** [comment]
One thing I don't understand: is GitHub available in zh-CN or is it English-only?

**Comment by fregante** [comment]
I'm probably going to remove the extra languages because github.com is in English only.
